#!/bin/sh

############################################################################
#  WARNING! WARNING! WARNING!                                              #
#                                                                          #
#  The contents of this file are automatically generated by the build      #
#  system. Do not make any changes directly to this file; such changes     #
#  will be silently ignored and overwritten!                               #
#                                                                          #
#  The template whence this file's contents were derived are in a file     #
#  of the same name with ".in" appended.                                   #
############################################################################

# build_debs.sh
#
#  Build Debian packages.
#
#   (C) Copyright 2021 Fred Gleason <fredg@paravelsystems.com>
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License version 2 as
#   published by the Free Software Foundation.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public
#   License along with this program; if not, write to the Free Software
#   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#

tar -zvxf lwmon-0.0.0.tar.gz
mv lwmon-0.0.0.tar.gz lwmon_0.0.0.orig.tar.gz

cd lwmon-0.0.0
dpkg-buildpackage -us -uc
cd ..

rm -rf lwmon-0.0.0
